### ISSUE TITLE
Refactor overall folder structure

### ISSUE THREAD

**Issue by mvmjacobs** [lgmf/finances#8]
[Angular Guide](https://angular.io/guide/styleguide#overall-structural-guidelines).

**Comment by lgmf** [comment]
Whats wrong?

**Comment by mvmjacobs** [comment]
The current structure doesn't follow the guide. It's not really a problem.

**Comment by lgmf** [comment]
I'll change the label and follow de Guide then

**Comment by mvmjacobs** [comment]
Waiting PR review
